# sqlite usage
version: '3'

services:
  jchat:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # https://github.com/docker/compose/issues/1837#issuecomment-316896858
        # refer to .env file,
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_WS_URL=${REACT_APP_WS_URL}
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3030
    volumes:
      - ./chatapi.sqlite/:/app/chatapi.sqlite
    ports:
      - 3030:3030
    # command: npm start

  chatapi:
    # git clone https://github.com/JaosnHsieh/chatapi.git in ../ path first
    build: ../chatapi/
    restart: always
    environment:
      NODE_ENV: production
      IS_USE_SQLITE: 'true'
      # DB_HOSTNAME: ${localip}
      # DB_NAME: chat-api
      # DB_USERNAME: root
      # DB_PASSWORD: rootpass
      PORT: 3306
    volumes:
      - ../chatapi/chatapi.sqlite/:/app/chatapi.sqlite
    ports:
      - 3306:3306
    # command: npm start
